#swarm -f /home/sevillas2/git/Pipeliner/testing/submit_fq.slurm --verbose 1

#module load sratoolkit; fasterq-dump SRR1544075 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1548811 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659951 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659952 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659953 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659954 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659955 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659956 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659957 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659958 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
#module load sratoolkit; fasterq-dump SRR1659959 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq

module load sratoolkit; fasterq-dump SRR1659960 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
module load sratoolkit; fasterq-dump SRR1659961 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq

module load sratoolkit; fasterq-dump SRR1659962 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
module load sratoolkit; fasterq-dump SRR1659963 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq

module load sratoolkit; fasterq-dump SRR1659964 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
module load sratoolkit; fasterq-dump SRR1659965 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq

module load sratoolkit; fasterq-dump SRR1659966 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
module load sratoolkit; fasterq-dump SRR1659967 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
module load sratoolkit; fasterq-dump SRR1659968 -O /data/CCBR_Pipeliner/sandbox/arriba/fastq -t /data/CCBR_Pipeliner/sandbox/arriba/fastq
