swarm -f /home/sevillas2/git/Pipeliner/testing/submit_gz.slurm --verbose 1

gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1544075_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1544075_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1548811_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1548811_2.fastq

gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659951_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659951_2.fastq

gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659952_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659952_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659953_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659953_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659954_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659954_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659955_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659955_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659956_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659956_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659957_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659957_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659958_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659958_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659959_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659959_2.fastq

gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659960_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659960_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659961_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659961_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659962_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659962_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659963_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659963_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659964_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659964_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659965_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659965_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659966_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659966_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659967_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659967_2.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659968_1.fastq
gzip /data/CCBR_Pipeliner/sandbox/arriba/fastq/SRR1659968_2.fastq
