---
title: "DEG"
author: "Vishal Koparde, PhD [CCBR]"
output: 
  html_document:
    toc: true
    toc_float: true
params:
  degfile: "~/../../Volumes/projects-1/ccbr1066/deg_012021/DEG_Mock-KO_0.5_0.5/limma_DEG_Mock-KO_all_genes.txt"
  output_dir: "~/../../Volumes/projects-1/ccbr1066/analysis/ora_vs_gsea_test/"
  contrast_id: "Mock.KO"
  species: "Homo sapiens"
  pval: 0.05
  fc: 2
editor_options: 
  chunk_output_type: console
---

## `r deg_file`

```{r include=FALSE}
library("tidyverse")
library("stats")
library("affy")
library("DESeq2")
library("edgeR")
library("DT")
library("ggplot2")
library("EnhancedVolcano")
library("msigdbr")
library("enrichplot")
library("clusterProfiler")
```

######################################################################
# Functions
######################################################################
```{r functions, include=FALSE}
readdegfile<-function(fn){
  x=read.csv(fn,header=TRUE,sep="\t")
  return(as.data.frame(x))
}
deg2geneList<-function(deg){
  gl=as.data.frame(deg$gsea_ranking_score)
  gl$GN=deg$gene
  colnames(gl)=c("Rank","GeneName")
  gl$absRank=abs(gl$Rank)
  gl=gl[order(gl$absRank,decreasing = TRUE),]
  gl=gl[match(unique(gl$GeneName),gl$GeneName),]
  geneList=gl$Rank
  names(geneList)=as.character(gl$GeneName)
  geneList <- sort(geneList, decreasing = TRUE)
  return(geneList)
}

gsea_plus_plot <- function(gl,t2g,ttl,fn){
  result=GSEA(geneList = gl,TERM2GENE = t2g,eps = 0)
  resultdf=as.data.frame(result)
  write.table(resultdf,file=fn,quote=FALSE,sep="\t",row.names = FALSE,col.names = TRUE)
  dotplot(result,title=ttl,font.size = 8, showCategory=10)
}

ora_plus_plot <- function(gl,t2g,ttl,fn){
  result=enricher(gene=gl,TERM2GENE=t2g,pvalueCutoff = 0.1)
  dotplot(result,title=ttl,font.size = 8, showCategory=10)
}
```

######################################################################
# main code
######################################################################
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

#set params
deg_file = params$degfile
p_val = params$pval
out_dir = params$output_dir
species = params$species
fc = params$fc
contrast_id = params$contrast_id

# read deg
deg=readdegfile(deg_file)
```

#create gene and annotated lists
```{r}
#subset significant genes for GSEA
siggenes=deg[deg$fdr <= p_val & (deg$fc < (-1*fc) | deg$fc > fc),]
sigGeneList=siggenes$gene

#set genelist for ORA
geneList=deg2geneList(deg)

#generate gene lists for C2 with subtypes biocarta, kegg, reactome, wiki
c2b=msigdbr(species = params$species, category = "C2", subcategory = "BIOCARTA") %>% 
  dplyr::select(gs_name,gene_symbol)

c2k=msigdbr(species = params$species, category = "C2", subcategory = "KEGG") %>% 
  dplyr::select(gs_name,gene_symbol)

c2r=msigdbr(species = params$species, category = "C2", subcategory = "REACTOME") %>%
  dplyr::select(gs_name,gene_symbol)

c2w=msigdbr(species = params$species, category = "C2", subcategory = "WIKIPATHWAYS") %>%
  dplyr::select(gs_name,gene_symbol)

#generate gene lists for C5 with subtypes MF, BP, CC
c5gomf=msigdbr(species = params$species,  category = "C5", subcategory = "GO:MF") %>% dplyr::select(gs_name,gene_symbol)
c5gobp=msigdbr(species = params$species,  category = "C5", subcategory = "GO:BP") %>% dplyr::select(gs_name,gene_symbol)
c5gocc=msigdbr(species = params$species,  category = "C5", subcategory = "GO:CC") %>% dplyr::select(gs_name,gene_symbol)
```

## C2:BIOCARTA
```{r c2b,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c2b,ttl="GSEA:C2:BIOCARTA",fn=paste(out_dir,contrast_id,".c2b.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c2b,ttl="ORA:C2:BIOCARTA",fn=paste(out_dir,contrast_id,".c2b.ora.results.txt",sep=""))
```

## C2:KEGG
```{r c2k,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c2k,ttl="GSEA:C2:KEGG",fn=paste(out_dir,contrast_id,".c2k.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c2k,ttl="ORA:C2:KEGG",fn=paste(out_dir,contrast_id,".c2k.ora.results.txt",sep=""))

```

## C2:REACTOME
```{r c2r,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c2r,ttl="GSEA:C2:REACTOME",fn=paste(out_dir,contrast_id,".c2r.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c2r,ttl="ORA:C2:REACTOME",fn=paste(out_dir,contrast_id,".c2r.ora.results.txt",sep=""))
```

## C2:WIKIPATHWAYS
```{r c2w,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c2w,ttl="GSEA:C2:WIKIPATHWAYS",fn=paste(out_dir,contrast_id,".c2w.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c2w,ttl="ORA:C2:WIKIPATHWAYS",fn=paste(out_dir,contrast_id,".c2w.ora.results.txt",sep=""))
```

## C5:GO:MF
```{r gomf,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c5gomf,ttl="GSEA:GO:MF",fn=paste(out_dir,contrast_id,".c5gomf.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c5gomf,ttl="ORA:GO:MF",fn=paste(out_dir,contrast_id,".c5gomf.ora.results.txt",sep=""))
```

## C5:GO:BP
```{r gobp,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c5gobp,ttl="GSEA:GO:BP",fn=paste(out_dir,contrast_id,".c5gobp.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c5gobp,ttl="ORA:GO:BP",fn=paste(out_dir,contrast_id,".c5gobp.ora.results.txt",sep=""))
```

## C5:GO:CC
```{r gobp,echo=FALSE}
gsea_plus_plot(gl=geneList,t2g=c5gobp,ttl="GSEA:GO:CC",fn=paste(out_dir,contrast_id,".c5gocc.gsea.results.txt",sep=""))
ora_plus_plot(gl=sigGeneList,t2g=c5gobp,ttl="ORA:GO:CC",fn=paste(out_dir,contrast_id,".c5gocc.ora.results.txt",sep=""))
```
